
public inherited sharing class ConstantsClass {

    //Custom Settings Variables
    public static final String FREE_PLAN_KEY_STRING = 'Free_Plan_Key';

    //Apex Class Name Variables
    public static final String BIKE_CURRENCY_CONTROLLER_STRING = 'BikeChangeCurrencyController';

    //Errors Variables
    public static final String PLEASE_ADD_SUPPORT_CURRENCY_STRING = 'Please add support for this currency if necessary: ';
}